# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
# Enable version updates for GitHub Actions workflows
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: weekly
    ignore:
      # Ignore updates for dependencies with names containing "github-script"
      - dependency-name: "*github-script*"

